### ISSUE TITLE
Links on hex.pm point to naughtygram

### ISSUE THREAD

**Issue by bradylove** [Zensavona/hr#1]
The "Docs" and "GitHub" links on hex.pm for hr (https://hex.pm/packages/hr) point to the repository for naughtygram (https://hexdocs.pm/naughtygram and https://github.com/zensavona/naughtygram)

**Comment by Zensavona** [comment]
I know, I made a type copying boilerplate `mix.exs` stuff over when creating that in a hurry and there's a known bug in hex.pm where changes to links do not show up. Thanks though @bradylove :heart:
